### ISSUE TITLE
trep01-sp

### ISSUE THREAD

**Issue by blbin** [nvbach91/4IZ278-2022-2023-LS#275]
# webový FTP klient
### popis aplikace
Cílem mé semestrální práce bude vytvořit funkčního webového FTP klienta, který navíc umožní uživatelům spravovat a ukládat svá FTP připojení na svůj profil a mít k ním tak přístup z kteréhokoliv moderního webového prohlížeče a nebo je dokonce sdílet s dalšími uživateli. 
Uživatel se tedy bude moci rovnou připojit ke svému FTP serveru, a nebo se zaregistrovat/přihlásit, přidat ftp spojení, nebo vybrat již uložené a připojit se k vybranému serveru a manipulovat se soubory jako v klasickém FTP klientu. 

## architektura aplikace
Cílem bude vytvořit JS AJAX klienta který bude pomocí  API požadavků komunikovat s PHP severem. Ten bude komunikovat s Databází a FTP servrem uživatele. 
Avšak aby se obešla bežné omezení PHP (upload_max_filesize) bude klient _nejspíše_ nahrávat soubory přímo přes FTP.

- webový server - **Apache**
- backend - **PHP 8+**
- databáze - **MySQL/MariaDB**
- fontend - **HTML, CSS, JS (jquery)** 

*_Je možné, že při vývoje narazím na další vhodné _(požadavky práce povolené)_ technogie nebo knihovny, jejich případné použití bude k nalezení v dokumentaci projektu._

### usecase diagram
![Diagram bez názvu(17)](https://user-images.githubusercontent.com/60446782/233868233-26d5a738-d36e-4fce-80c7-49b5123f35f9.jpg)

### procesní diagram
![Diagram bez názvu(16)](https://user-images.githubusercontent.com/60446782/233867902-e38b5907-afd4-4b14-80f5-ddcc57418865.jpg)

### sekvenční diagram
![Diagram bez názvu(20)](https://user-images.githubusercontent.com/60446782/233868421-4f442faf-59af-408e-97b1-dbd58f2ebe10.jpg)

## wireframy
![Diagram bez názvu(10)](https://user-images.githubusercontent.com/60446782/233866574-6ae571bf-8b28-4081-93d3-2c6626946ac6.jpg)

![Diagram bez názvu(19)](https://user-images.githubusercontent.com/60446782/233868380-57dd26cc-b624-4e9b-9941-0a3765a21f25.jpg)

![Diagram bez názvu(8)](https://user-images.githubusercontent.com/60446782/233866522-e1b07658-1777-4308-92ed-56dae5400a4c.jpg)

![Diagram bez názvu(9)](https://user-images.githubusercontent.com/60446782/233866552-42b256ca-5eff-470e-8752-ccc6ff210414.jpg)

### logický model
![dfsfsdfsdf](https://user-images.githubusercontent.com/60446782/233866742-c4e1861f-10a7-4d00-beab-dc9cb50df792.png)

### fyzický model 
![sfdsfdsgdsdf](https://user-images.githubusercontent.com/60446782/233866789-5e504704-7f36-4717-8922-b8b17fe5291f.PNG)

## *_možné rozšíření_

*Když mi zbude čas, rád bych nad rámec věcí výše implemetoval tagy dle kterých by šlo filtrovat a řadit jednotlivé přístupy. Nebo historii jednotlivých operací na FTP. Či zapamatování oblíbených souborů/složek _(u tohoto ale zatím nevím, jak by to bylo technicky proveditelné)._

**Comment by nvbach91** [comment]
Já jsem myslel, že aplikace umožní správu FTP připojení (username/password/private-key/...), připojovat se na FTP server pomocí nich, a spravovat soubory na tom FTP, něco jako WinSCP nebo FileZilla? Tomu zatím moc neodpovídá schéma DB.

**Comment by blbin** [comment]
Ano, je to tak. Udaje pro připojení jsou v tabulce accesses. Udaje s souborech se do webové databáze ukládat nebudou a budou se brát přímo z ftp serveru. Protože je vždy potřeba pracovat s aktuálním stavem serveru a soubory na něm. (stejně jako u klientů WinSCP nebo FileZilla)
Databáze slouží ke správě udájů o uživatelských účtech, k ukládání a sdílení přístupů k ftp serveru.
